# Generated by Django 4.0.2 on 2022-02-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_brand_id_alter_brand_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='car_Type',
            field=models.CharField(default='car type', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine',
            field=models.CharField(default='engine', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seater',
            field=models.CharField(default='seater', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='rental_price',
            field=models.PositiveIntegerField(),
        ),
    ]
