# Generated by Django 4.0.2 on 2022-02-25 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_favourite_pvehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='pVehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.popularvehicle'),
        ),
    ]
