# Generated by Django 4.0.2 on 2022-02-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_favourite_pvehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='pVehicle',
        ),
    ]
