# Generated by Django 4.0.2 on 2022-02-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
