# Generated by Django 4.0.2 on 2022-03-09 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_advertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='pVehicle',
            field=models.ForeignKey(
                default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.popularvehicle'),
        ),
    ]
