# Generated by Django 4.0.2 on 2022-03-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_favourite_pvehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='pVehicle',
        ),
    ]
