# Generated by Django 4.0.2 on 2022-03-31 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rent',
        ),
    ]
