# Generated by Django 4.0.2 on 2022-04-13 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_remove_rent_document_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='user',
        ),
    ]
