///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AdvertiseVehicle {
/*
{
  "id": 1,
  "title": "Hyundai i20",
  "date": "2022-02-12T00:00:00Z",
  "image": "http://127.0.0.1:8000/media/vehiclesImages/Hyundai_i20_Vb6oZom.png",
  "seater": "4",
  "car_Type": "SUV",
  "engine": "Manual",
  "rental_price": 2500,
  "descrition": "Hyundai i20 is a 5 seater Hatchback.  It is available in 24 variants, 3 engine options that are BS6 compliant, and 2 transmission options: Manual & Automatic. Other key specifications of the i20 include a curb weight and boot space of 311 Liters.",
  "Brand": 3
} 
*/

  int? id;
  String? title;
  String? date;
  String? image;
  String? seater;
  String? carType;
  String? engine;
  int? rentalPrice;
  String? descrition;
  int? Brand;

  AdvertiseVehicle({
    this.id,
    this.title,
    this.date,
    this.image,
    this.seater,
    this.carType,
    this.engine,
    this.rentalPrice,
    this.descrition,
    this.Brand,
  });
  AdvertiseVehicle.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    date = json['date']?.toString();
    image = json['image']?.toString();
    seater = json['seater']?.toString();
    carType = json['car_Type']?.toString();
    engine = json['engine']?.toString();
    rentalPrice = json['rental_price']?.toInt();
    descrition = json['descrition']?.toString();
    Brand = json['Brand']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['date'] = date;
    data['image'] = image;
    data['seater'] = seater;
    data['car_Type'] = carType;
    data['engine'] = engine;
    data['rental_price'] = rentalPrice;
    data['descrition'] = descrition;
    data['Brand'] = Brand;
    return data;
  }
}

class Advertise {
/*
{
  "id": 1,
  "title": "Hyundai Offer",
  "image": "http://127.0.0.1:8000/media/AdvertiseImages/hyundai_i20_offers.jpg",
  "description": "Presenting you the offer for Hyundai Car",
  "price": 1500,
  "vehicle": {
    "id": 1,
    "title": "Hyundai i20",
    "date": "2022-02-12T00:00:00Z",
    "image": "http://127.0.0.1:8000/media/vehiclesImages/Hyundai_i20_Vb6oZom.png",
    "seater": "4",
    "car_Type": "SUV",
    "engine": "Manual",
    "rental_price": 2500,
    "descrition": "Hyundai i20 is a 5 seater Hatchback.  It is available in 24 variants, 3 engine options that are BS6 compliant, and 2 transmission options: Manual & Automatic. Other key specifications of the i20 include a curb weight and boot space of 311 Liters.",
    "Brand": 3
  }
} 
*/

  int? id;
  String? title;
  String? image;
  String? description;
  int? price;
  AdvertiseVehicle? vehicle;

  Advertise({
    this.id,
    this.title,
    this.image,
    this.description,
    this.price,
    this.vehicle,
  });
  Advertise.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    image = json['image']?.toString();
    description = json['description']?.toString();
    price = json['price']?.toInt();
    vehicle = (json['vehicle'] != null)
        ? AdvertiseVehicle.fromJson(json['vehicle'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['image'] = image;
    data['description'] = description;
    data['price'] = price;
    if (vehicle != null) {
      data['vehicle'] = vehicle!.toJson();
    }
    return data;
  }
}
