///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Brand {
/*
{
  "id": 3,
  "image": "/media/Brands/Hyundai_logo_2l75hBt.png",
  "title": "Hyundai",
  "date": "2022-02-12T00:00:00Z"
} 
*/

  int? id;
  String? image;
  String? title;
  String? date;

  Brand({
    this.id,
    this.image,
    this.title,
    this.date,
  });
  Brand.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    image = json['image']?.toString();
    title = json['title']?.toString();
    date = json['date']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['image'] = image;
    data['title'] = title;
    data['date'] = date;
    return data;
  }
}
