///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BrandVehiclesVehiclesBrand {
/*
{
  "id": 5,
  "image": "http://127.0.0.1:8000/media/Brands/Kia_logo_cdzLlAo.png",
  "title": "Kia",
  "date": "2022-02-12T00:00:00Z"
} 
*/

  int? id;
  String? image;
  String? title;
  String? date;

  BrandVehiclesVehiclesBrand({
    this.id,
    this.image,
    this.title,
    this.date,
  });
  BrandVehiclesVehiclesBrand.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    image = json['image']?.toString();
    title = json['title']?.toString();
    date = json['date']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['image'] = image;
    data['title'] = title;
    data['date'] = date;
    return data;
  }
}

class BrandVehiclesVehicles {
/*
{
  "id": 3,
  "title": "Kia Sportage",
  "date": "2022-02-17T00:00:00Z",
  "image": "http://127.0.0.1:8000/media/vehiclesImages/kia-sportage_jTBQlI0.png",
  "seater": "5",
  "car_Type": "SUV",
  "engine": "Manual",
  "rental_price": 2500,
  "descrition": "The new Kia Sportage elegance meets practicality and combines high comfort and spaciousness, with class and innovativeness all in one revolutionary design. A striking design with stunning curves, accentuated with eye-catching colors Sportage takes the driving experience to a whole new level.",
  "Brand": {
    "id": 5,
    "image": "http://127.0.0.1:8000/media/Brands/Kia_logo_cdzLlAo.png",
    "title": "Kia",
    "date": "2022-02-12T00:00:00Z"
  }
} 
*/

  int? id;
  String? title;
  String? date;
  String? image;
  String? seater;
  String? carType;
  String? engine;
  int? rentalPrice;
  String? descrition;
  BrandVehiclesVehiclesBrand? Brand;

  BrandVehiclesVehicles({
    this.id,
    this.title,
    this.date,
    this.image,
    this.seater,
    this.carType,
    this.engine,
    this.rentalPrice,
    this.descrition,
    this.Brand,
  });
  BrandVehiclesVehicles.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    date = json['date']?.toString();
    image = json['image']?.toString();
    seater = json['seater']?.toString();
    carType = json['car_Type']?.toString();
    engine = json['engine']?.toString();
    rentalPrice = json['rental_price']?.toInt();
    descrition = json['descrition']?.toString();
    Brand = (json['Brand'] != null)
        ? BrandVehiclesVehiclesBrand.fromJson(json['Brand'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['date'] = date;
    data['image'] = image;
    data['seater'] = seater;
    data['car_Type'] = carType;
    data['engine'] = engine;
    data['rental_price'] = rentalPrice;
    data['descrition'] = descrition;
    if (Brand != null) {
      data['Brand'] = Brand!.toJson();
    }
    return data;
  }
}

class BrandVehicles {
/*
{
  "id": 5,
  "image": "http://127.0.0.1:8000/media/Brands/Kia_logo_cdzLlAo.png",
  "title": "Kia",
  "date": "2022-02-12T00:00:00Z",
  "vehicles": [
    {
      "id": 3,
      "title": "Kia Sportage",
      "date": "2022-02-17T00:00:00Z",
      "image": "http://127.0.0.1:8000/media/vehiclesImages/kia-sportage_jTBQlI0.png",
      "seater": "5",
      "car_Type": "SUV",
      "engine": "Manual",
      "rental_price": 2500,
      "descrition": "The new Kia Sportage elegance meets practicality and combines high comfort and spaciousness, with class and innovativeness all in one revolutionary design. A striking design with stunning curves, accentuated with eye-catching colors Sportage takes the driving experience to a whole new level.",
      "Brand": {
        "id": 5,
        "image": "http://127.0.0.1:8000/media/Brands/Kia_logo_cdzLlAo.png",
        "title": "Kia",
        "date": "2022-02-12T00:00:00Z"
      }
    }
  ]
} 
*/

  int? id;
  String? image;
  String? title;
  String? date;
  List<BrandVehiclesVehicles?>? vehicles;

  BrandVehicles({
    this.id,
    this.image,
    this.title,
    this.date,
    this.vehicles,
  });
  BrandVehicles.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    image = json['image']?.toString();
    title = json['title']?.toString();
    date = json['date']?.toString();
    if (json['vehicles'] != null) {
      final v = json['vehicles'];
      final arr0 = <BrandVehiclesVehicles>[];
      v.forEach((v) {
        arr0.add(BrandVehiclesVehicles.fromJson(v));
      });
      vehicles = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['image'] = image;
    data['title'] = title;
    data['date'] = date;
    if (vehicles != null) {
      final v = vehicles;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['vehicles'] = arr0;
    }
    return data;
  }
}
