///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CartCartvehiclesVehicle {
/*
{
  "id": 5,
  "title": "Kia Sonet",
  "date": "2022-02-24T00:00:00Z",
  "image": "/media/vehiclesImages/kia_sonet_qaD8wwX.png",
  "seater": "5",
  "car_Type": "SUV",
  "engine": "Automatic",
  "rental_price": 1800,
  "descrition": "KIA SONET is hitting a tremendous benchmark among the sub-compact SUV segment. The Kia Sonet performance scales with refined 1.5 CRDi Diesel Engine available in 6 Speed MT (100 PS Power) and first-in Segment (115 PS Power) 6 Speed advance AT. The power of 120 PS combined with the option of 6iMT & 7DCT Smartstream engines make driving comfortable.",
  "Brand": 5
} 
*/

  int? id;
  String? title;
  String? date;
  String? image;
  String? seater;
  String? carType;
  String? engine;
  int? rentalPrice;
  String? descrition;
  int? Brand;

  CartCartvehiclesVehicle({
    this.id,
    this.title,
    this.date,
    this.image,
    this.seater,
    this.carType,
    this.engine,
    this.rentalPrice,
    this.descrition,
    this.Brand,
  });
  CartCartvehiclesVehicle.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    date = json['date']?.toString();
    image = json['image']?.toString();
    seater = json['seater']?.toString();
    carType = json['car_Type']?.toString();
    engine = json['engine']?.toString();
    rentalPrice = json['rental_price']?.toInt();
    descrition = json['descrition']?.toString();
    Brand = json['Brand']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['date'] = date;
    data['image'] = image;
    data['seater'] = seater;
    data['car_Type'] = carType;
    data['engine'] = engine;
    data['rental_price'] = rentalPrice;
    data['descrition'] = descrition;
    data['Brand'] = Brand;
    return data;
  }
}

class CartCartvehiclesCart {
/*
{
  "id": 3,
  "total": 2500,
  "isComplete": false,
  "date": "2022-03-07",
  "user": 31
} 
*/

  int? id;
  int? total;
  bool? isComplete;
  String? date;
  int? user;

  CartCartvehiclesCart({
    this.id,
    this.total,
    this.isComplete,
    this.date,
    this.user,
  });
  CartCartvehiclesCart.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    total = json['total']?.toInt();
    isComplete = json['isComplete'];
    date = json['date']?.toString();
    user = json['user']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['total'] = total;
    data['isComplete'] = isComplete;
    data['date'] = date;
    data['user'] = user;
    return data;
  }
}

class CartCartvehicles {
/*
{
  "id": 5,
  "price": 3500,
  "quntity": 1,
  "subtotal": 3500,
  "cart": {
    "id": 3,
    "total": 2500,
    "isComplete": false,
    "date": "2022-03-07",
    "user": 31
  },
  "vehicle": [
    {
      "id": 5,
      "title": "Kia Sonet",
      "date": "2022-02-24T00:00:00Z",
      "image": "/media/vehiclesImages/kia_sonet_qaD8wwX.png",
      "seater": "5",
      "car_Type": "SUV",
      "engine": "Automatic",
      "rental_price": 1800,
      "descrition": "KIA SONET is hitting a tremendous benchmark among the sub-compact SUV segment. The Kia Sonet performance scales with refined 1.5 CRDi Diesel Engine available in 6 Speed MT (100 PS Power) and first-in Segment (115 PS Power) 6 Speed advance AT. The power of 120 PS combined with the option of 6iMT & 7DCT Smartstream engines make driving comfortable.",
      "Brand": 5
    }
  ]
} 
*/

  int? id;
  int? price;
  int? quntity;
  int? subtotal;
  CartCartvehiclesCart? cart;
  List<CartCartvehiclesVehicle?>? vehicle;

  CartCartvehicles({
    this.id,
    this.price,
    this.quntity,
    this.subtotal,
    this.cart,
    this.vehicle,
  });
  CartCartvehicles.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    price = json['price']?.toInt();
    quntity = json['quntity']?.toInt();
    subtotal = json['subtotal']?.toInt();
    cart = (json['cart'] != null)
        ? CartCartvehiclesCart.fromJson(json['cart'])
        : null;
    if (json['vehicle'] != null) {
      final v = json['vehicle'];
      final arr0 = <CartCartvehiclesVehicle>[];
      v.forEach((v) {
        arr0.add(CartCartvehiclesVehicle.fromJson(v));
      });
      vehicle = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['price'] = price;
    data['quntity'] = quntity;
    data['subtotal'] = subtotal;
    if (cart != null) {
      data['cart'] = cart!.toJson();
    }
    if (vehicle != null) {
      final v = vehicle;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['vehicle'] = arr0;
    }
    return data;
  }
}

class Cart {
/*
{
  "id": 3,
  "total": 2500,
  "isComplete": false,
  "date": "2022-03-07",
  "user": 31,
  "cartvehicles": [
    {
      "id": 5,
      "price": 3500,
      "quntity": 1,
      "subtotal": 3500,
      "cart": {
        "id": 3,
        "total": 2500,
        "isComplete": false,
        "date": "2022-03-07",
        "user": 31
      },
      "vehicle": [
        {
          "id": 5,
          "title": "Kia Sonet",
          "date": "2022-02-24T00:00:00Z",
          "image": "/media/vehiclesImages/kia_sonet_qaD8wwX.png",
          "seater": "5",
          "car_Type": "SUV",
          "engine": "Automatic",
          "rental_price": 1800,
          "descrition": "KIA SONET is hitting a tremendous benchmark among the sub-compact SUV segment. The Kia Sonet performance scales with refined 1.5 CRDi Diesel Engine available in 6 Speed MT (100 PS Power) and first-in Segment (115 PS Power) 6 Speed advance AT. The power of 120 PS combined with the option of 6iMT & 7DCT Smartstream engines make driving comfortable.",
          "Brand": 5
        }
      ]
    }
  ]
} 
*/

  int? id;
  int? total;
  bool? isComplete;
  String? date;
  int? user;
  List<CartCartvehicles?>? cartvehicles;

  Cart({
    this.id,
    this.total,
    this.isComplete,
    this.date,
    this.user,
    this.cartvehicles,
  });
  Cart.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    total = json['total']?.toInt();
    isComplete = json['isComplete'];
    date = json['date']?.toString();
    user = json['user']?.toInt();
    if (json['cartvehicles'] != null) {
      final v = json['cartvehicles'];
      final arr0 = <CartCartvehicles>[];
      v.forEach((v) {
        arr0.add(CartCartvehicles.fromJson(v));
      });
      cartvehicles = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['total'] = total;
    data['isComplete'] = isComplete;
    data['date'] = date;
    data['user'] = user;
    if (cartvehicles != null) {
      final v = cartvehicles;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['cartvehicles'] = arr0;
    }
    return data;
  }
}
