///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PopularVehiclesBrand {
/*
{
  "id": 5,
  "title": "Kia",
  "date": "2022-02-12"
} 
*/

  int? id;
  String? title;
  String? date;

  PopularVehiclesBrand({
    this.id,
    this.title,
    this.date,
  });
  PopularVehiclesBrand.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    date = json['date']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['date'] = date;
    return data;
  }
}

class PopularVehicles {
/*
{
  "id": 5,
  "title": "Kia Sonet",
  "date": "2022-02-24",
  "image": "http://127.0.0.1:8000/media/vehiclesImages/kia_sonet.png",
  "seater": "5",
  "car_Type": "SUV",
  "engine": "Automatic",
  "rental_price": 1800,
  "descrition": "KIA SONET is hitting a tremendous benchmark among the sub-compact SUV segment. The Kia Sonet performance scales with refined 1.5 CRDi Diesel Engine available in 6 Speed MT (100 PS Power) and first-in Segment (115 PS Power) 6 Speed advance AT. The power of 120 PS combined with the option of 6iMT & 7DCT Smartstream engines make driving comfortable.",
  "Brand": {
    "id": 5,
    "title": "Kia",
    "date": "2022-02-12"
  }
} 
*/

  int? id;
  String? title;
  String? date;
  String? image;
  String? seater;
  String? carType;
  String? engine;
  int? rentalPrice;
  String? descrition;
  PopularVehiclesBrand? Brand;

  PopularVehicles({
    this.id,
    this.title,
    this.date,
    this.image,
    this.seater,
    this.carType,
    this.engine,
    this.rentalPrice,
    this.descrition,
    this.Brand,
  });
  PopularVehicles.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    date = json['date']?.toString();
    image = json['image']?.toString();
    seater = json['seater']?.toString();
    carType = json['car_Type']?.toString();
    engine = json['engine']?.toString();
    rentalPrice = json['rental_price']?.toInt();
    descrition = json['descrition']?.toString();
    Brand = (json['Brand'] != null)
        ? PopularVehiclesBrand.fromJson(json['Brand'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['date'] = date;
    data['image'] = image;
    data['seater'] = seater;
    data['car_Type'] = carType;
    data['engine'] = engine;
    data['rental_price'] = rentalPrice;
    data['descrition'] = descrition;
    if (Brand != null) {
      data['Brand'] = Brand!.toJson();
    }
    return data;
  }
}

class Popular {
/*
{
  "id": 1,
  "date": "2022-02-24T17:33:46.081838Z",
  "vehicle": 5,
  "vehicles": {
    "id": 5,
    "title": "Kia Sonet",
    "date": "2022-02-24",
    "image": "http://127.0.0.1:8000/media/vehiclesImages/kia_sonet.png",
    "seater": "5",
    "car_Type": "SUV",
    "engine": "Automatic",
    "rental_price": 1800,
    "descrition": "KIA SONET is hitting a tremendous benchmark among the sub-compact SUV segment. The Kia Sonet performance scales with refined 1.5 CRDi Diesel Engine available in 6 Speed MT (100 PS Power) and first-in Segment (115 PS Power) 6 Speed advance AT. The power of 120 PS combined with the option of 6iMT & 7DCT Smartstream engines make driving comfortable.",
    "Brand": {
      "id": 5,
      "title": "Kia",
      "date": "2022-02-12"
    }
  },
  "favourite": true
} 
*/

  int? id;
  String? date;
  int? vehicle;
  PopularVehicles? vehicles;
  bool? favourite;

  Popular({
    this.id,
    this.date,
    this.vehicle,
    this.vehicles,
    this.favourite,
  });
  Popular.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    date = json['date']?.toString();
    vehicle = json['vehicle']?.toInt();
    vehicles = (json['vehicles'] != null)
        ? PopularVehicles.fromJson(json['vehicles'])
        : null;
    favourite = json['favourite'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['date'] = date;
    data['vehicle'] = vehicle;
    if (vehicles != null) {
      data['vehicles'] = vehicles!.toJson();
    }
    data['favourite'] = favourite;
    return data;
  }
}
