///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class VehicleBrand {
/*
{
  "id": 3,
  "title": "Hyundai",
  "date": "2022-02-12"
} 
*/

  int? id;
  String? title;
  String? date;

  VehicleBrand({
    this.id,
    this.title,
    this.date,
  });
  VehicleBrand.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    date = json['date']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['date'] = date;
    return data;
  }
}

class Vehicle {
/*
{
  "id": 1,
  "title": "Hyundai i20",
  "date": "2022-02-12",
  "image": "/media/vehiclesImages/Hyundai_i20.png",
  "seater": "4",
  "car_Type": "SUV",
  "engine": "Manual",
  "rental_price": 2500,
  "descrition": "Hyundai i20 is a 5 seater Hatchback.  It is available in 24 variants, 3 engine options that are BS6 compliant, and 2 transmission options: Manual & Automatic. Other key specifications of the i20 include a curb weight and boot space of 311 Liters.",
  "Brand": {
    "id": 3,
    "title": "Hyundai",
    "date": "2022-02-12"
  },
  "favourite": false
} 
*/

  int? id;
  String? title;
  String? date;
  String? image;
  String? seater;
  String? carType;
  String? engine;
  int? rentalPrice;
  String? descrition;
  VehicleBrand? Brand;
  bool? favourite;

  Vehicle({
    this.id,
    this.title,
    this.date,
    this.image,
    this.seater,
    this.carType,
    this.engine,
    this.rentalPrice,
    this.descrition,
    this.Brand,
    this.favourite,
  });
  Vehicle.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    date = json['date']?.toString();
    image = json['image']?.toString();
    seater = json['seater']?.toString();
    carType = json['car_Type']?.toString();
    engine = json['engine']?.toString();
    rentalPrice = json['rental_price']?.toInt();
    descrition = json['descrition']?.toString();
    Brand =
        (json['Brand'] != null) ? VehicleBrand.fromJson(json['Brand']) : null;
    favourite = json['favourite'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['date'] = date;
    data['image'] = image;
    data['seater'] = seater;
    data['car_Type'] = carType;
    data['engine'] = engine;
    data['rental_price'] = rentalPrice;
    data['descrition'] = descrition;
    if (Brand != null) {
      data['Brand'] = Brand!.toJson();
    }
    data['favourite'] = favourite;
    return data;
  }
}
